name: Package Datapack

on:
  workflow_dispatch:
    inputs:  
    
      artifact_name:
        description: 'Compressed file name'
        required: true
        default: 'Ore_Plus-'

      artifact_path:
        description: 'Path to the files to upload'
        required: true
        default: 'src/*'

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.artifact_name }}
          path: ${{ github.event.inputs.artifact_path }}
