name: Package Datapack v2

on:
  workflow_dispatch:
    inputs:  
    
      artifact_name:
        description: 'Datapack name'
        required: true
        default: 'Ore_Plus_'

      artifact_path:
        description: 'Path of the datapack contents'
        required: true
        default: 'src/*'

jobs:

  main:
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.artifact_name }}
          path: ${{ github.event.inputs.artifact_path }}
