name: Package Datapack v3

on:
  workflow_dispatch:
    inputs:  
      artifact_version:
        description: 'Version of the datapack'
        required: true
        default: '2.'
      alpha_version:
        description: 'Alpha version number'
        required: false
        default: ''
      beta_version:
        description: 'Beta version number'
        required: false
        default: ''
      custom_name:
        description: 'Custom datapack name'
        required: false
        default: ''

jobs:

  upload_x2_edition:
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set artifact name
        id: set_artifact_name
        run: |
          if [ "${{ github.event.inputs.custom_name }}" != "" ]; then
            echo "##[set-output name=artifact_name;]${{ github.event.inputs.custom_name }}"
          elif [ "${{ github.event.inputs.alpha_version }}" != "" ]; then
            echo "##[set-output name=artifact_name;]Ore_Plus_x2-${{ github.event.inputs.artifact_version }}-Alpha${{ github.event.inputs.alpha_version }}"
          elif [ "${{ github.event.inputs.beta_version }}" != "" ]; then
            echo "##[set-output name=artifact_name;]Ore_Plus_x2-${{ github.event.inputs.artifact_version }}-Beta${{ github.event.inputs.beta_version }}"
          else
            echo "##[set-output name=artifact_name;]Ore_Plus_x2-${{ github.event.inputs.artifact_version }}"
          fi

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact_name.outputs.artifact_name }}
          path: 'src/x2/*'
      
  upload_x4_edition:
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set artifact name
        id: set_artifact_name
        run: |
          if [ "${{ github.event.inputs.custom_name }}" != "" ]; then
            echo "##[set-output name=artifact_name;]${{ github.event.inputs.custom_name }}"
          elif [ "${{ github.event.inputs.alpha_version }}" != "" ]; then
            echo "##[set-output name=artifact_name;]Ore_Plus_x4-${{ github.event.inputs.artifact_version }}-Alpha${{ github.event.inputs.alpha_version }}"
          elif [ "${{ github.event.inputs.beta_version }}" != "" ]; then
            echo "##[set-output name=artifact_name;]Ore_Plus_x4-${{ github.event.inputs.artifact_version }}-Beta${{ github.event.inputs.beta_version }}"
          else
            echo "##[set-output name=artifact_name;]Ore_Plus_x4-${{ github.event.inputs.artifact_version }}"
          fi

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact_name.outputs.artifact_name }}
          path: 'src/x4/*'
  
  upload_Ultra_edition:
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set artifact name
        id: set_artifact_name
        run: |
          if [ "${{ github.event.inputs.custom_name }}" != "" ]; then
            echo "##[set-output name=artifact_name;]${{ github.event.inputs.custom_name }}"
          elif [ "${{ github.event.inputs.alpha_version }}" != "" ]; then
            echo "##[set-output name=artifact_name;]Ore_Plus_Ultra-${{ github.event.inputs.artifact_version }}-Alpha${{ github.event.inputs.alpha_version }}"
          elif [ "${{ github.event.inputs.beta_version }}" != "" ]; then
            echo "##[set-output name=artifact_name;]Ore_Plus_Ultra-${{ github.event.inputs.artifact_version }}-Beta${{ github.event.inputs.beta_version }}"
          else
            echo "##[set-output name=artifact_name;]Ore_Plus_Ultra-${{ github.event.inputs.artifact_version }}"
          fi

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact_name.outputs.artifact_name }}
          path: 'src/Ultra/*'